FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

COPY services/shared ./services/shared

COPY services/api-gateway ./services/api-gateway

RUN npm install --workspaces

WORKDIR /app/services/api-gateway

EXPOSE 3001

CMD ["npm", "run", "dev"]
