FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

COPY services/shared ./services/shared

COPY services/post-service ./services/post-service

RUN npm install --workspaces

WORKDIR /app/services/post-service

EXPOSE 4001

CMD ["npm", "run", "dev"]
