FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

COPY services/shared ./services/shared

COPY services/user-service ./services/user-service

RUN npm install --workspaces

WORKDIR /app/services/user-service

EXPOSE 4000

CMD ["npm", "run", "dev"]
