FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

COPY services/shared ./services/shared

COPY services/asset-service ./services/asset-service

RUN npm install --workspaces

WORKDIR /app/services/

EXPOSE 4002

CMD ["npm", "run", "dev"]
